---
version: '3.7'

services:
  friendsdrinks-request-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.RequestService /app/config/dev.properties"

  friendsdrinks-membership-request-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.membership.RequestService /app/config/dev.properties"

  friendsdrinks-membership-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.membership.MembershipWriterService /app/config/dev.properties"

  friendsdrinks-meetup-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.meetup.WriterService /app/config/dev.properties"

  friendsdrinks-invitation-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.membership.InvitationWriterService /app/config/dev.properties"

  friendsdrinks-writer-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.WriterService /app/config/dev.properties"

  frontend-api:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    ports:
      - "32778:8080"
    command: "andrewgrant.friendsdrinks.frontend.Main /app/config/dev.properties"

  user-service:
    image: andyg001/friendsdrinksbackend:latest
    networks:
      - kafka-network
    volumes:
      - ${PWD}/dev-dockercompose.properties:/app/config/dev.properties
    command: "andrewgrant.friendsdrinks.user.Service /app/config/dev.properties"

networks:
  kafka-network:
    external: true
    name: kafka_default
